name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build hub image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/hub/Dockerfile
          tags: artifacthub/hub:test
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build scanner image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/scanner/Dockerfile
          tags: artifacthub/scanner:test
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build tracker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/tracker/Dockerfile
          tags: artifacthub/tracker:test
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
