name: CI

on:
  push:
    branches:
      - master

jobs:
  push-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_TOKEN }}

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/hub/Dockerfile
          tags: registry.heroku.com/stark-eyrie-63979/web
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push tracker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/tracker/Dockerfile
          tags: registry.heroku.com/stark-eyrie-63979/tracker
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push scanner image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/scanner/Dockerfile
          tags: registry.heroku.com/stark-eyrie-63979/scanner
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Build and push migrator image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./database/migrations/Dockerfile
          tags: registry.heroku.com/stark-eyrie-63979/migrator
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
