name: CI

on:
  push:
    branches:
      - master

jobs:
  push-to-heroku:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host

      - name: Start local Docker registry
        run: |
          docker run -d -p 5000:5000 --name registry registry:3

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_TOKEN }}

      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/hub/Dockerfile
          tags: |
            localhost:5000/web:latest
          push: true
          platforms: linux/amd64
          provenance: false

      - uses: imjasonh/setup-crane@v0.1

      - name: Get manifest from local registry
        run: |
          crane manifest localhost:5000/web:latest | jq

      # registry.heroku.com/stark-eyrie-63979/web
